#!/bin/bash -l
#SBATCH --job-name=rface_rndf
##SBATCH --partition=defq
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=8gb
#SBATCH --time=2:00:00
#SBATCH --gres=gpu:1

#SBATCH --mail-type=ALL
#SBATCH --mail-user=ben.zhao@data61.csiro.au

module load python/3.6.1
module load tensorflow/1.8.0-py36-gpu
module load cuda/9.0.176
module load cudnn/v7.1.4-cuda90

python ./tf_face_proba_full_repeat.py 0

## for X in $(seq 0 10); do sbatch tf_nn_proba_jobscript; done;
